version: '3.8'

services:
  psql-db:
    image: postgres:13
    container_name: psql-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: brikauto
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  projet:
    container_name: auto_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql-db:5432/brikauto
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - psql-db
    networks:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge
