#version: '3.8'
#
#services:
#  psql-db:
#    image: postgres:13
#    container_name: psql-db
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: brikauto
#    ports:
#      - '5432:5432'
#
#  projet:
#    image: brikauto:latest
#    ports:
#      - '8082:8082'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://psql-db:5432/brikauto
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: admin
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    depends_on:
#      - psql-db
#
#



version: '3.8'

services:
  psql-db:
    image: postgres:13
    container_name: psql-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: brikauto
    ports:
      - '5432:5432'

  projet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql-db:5432/brikauto
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - psql-db
